name: shelly

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GitHubMail: "80205889+dozzler555@users.noreply.github.com"
  GitHubName: "dozzler555"
  ddl: ${{ secrets.link }}
jobs:
  shellbot:
    runs-on: ubuntu-18.04

    steps:
     - name: Checkouts
       uses: actions/checkout@master
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
     #- uses: rokibhasansagar/slimhub_actions@main

     - name: Set Git Configs & Secrets
       run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global color.ui true
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

     - name: install requirements
       run: |
          pip3 install setuptools
          pip3 install Jupyter
          pip3 install nbconvert
          pip3 install idna_ssl
          pip3 install beautifulsoup4
          pip3 install aiohttp
          pip3 install git+git://github.com/AWConant/jikanpy.git
          sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
          sudo apt update -y
          sudo apt install mediainfo -y
          sudo apt-get install ffmpeg -y

     
     - name: link
       run: |
            
             aria2c $ddl
             jupyter nbconvert --to notebook --inplace --execute Untitled1.ipynb

     - name: wf
       run: |
            echo "kajal"
          
